version: "3.1"
networks:
  hy-net:
    external: true

services:
  redis6:
    image: redis:6.0.7
    restart: always
    container_name: redis6
    networks:
      hy-net:

    environment:
      - TZ=Asia/Shanghai
    ports:
      - 6378:6379
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data:/data
